server:
  port: 10100
  servlet:
    context-path: /sc-user


eureka:
  client:
    service-url:
      defaultZone: http://localhost:10020/eureka
  instance:
    prefer-ip-address: true


spring:
  application:
    name: sc-user
  datasource:
    platform: mysql
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:h2db
    username: root
    password: admin
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  h2:
    console:
      path: /h2
      enabled: true
