server:
  port: 10000
  servlet:
    context-path: /sc-gateway

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:10020/eureka/


spring:
  application:
    name: sc-gateway
  cloud:
    gateway:
      routes:
        - id: sc-user
          uri: lb://sc-user
          predicates:
            - Path=/sc-user/**


